{{-  if .Values.quote_api_service.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.quote_api_service.name}}
  namespace: {{.Values.quote_api_service.namespace}}
  annotations:
     "helm.sh/hook": post-install
     "helm.sh/hook-weight": "3"
     
 
spec:
   replicas: 3 
   selector:
     {{- with .Values.quote_api_service.labels}}
     matchLabels:
        {{- toYaml . | nindent 10 }}
     {{- end }}
   template:
      metadata:
         labels:
           {{- with .Values.quote_api_service.labels}}
              {{- toYaml . | nindent 10 }}
           {{- end }}
      spec:
        containers:
          - name: quote-api 
            image: {{.Values.image.LOCATION}}-docker.pkg.dev/{{.Values.image.PROJECT_ID}}/{{.Values.image.REPOSITORY_NAME}}/quote-api 
            ports:
            - containerPort: 8080
            envFrom:
              - secretRef:
                   name: {{.Values.quote_api_service.secretRef}}

{{- end }}
            