apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: quote-ns

spec:
  provider:
    gcpsm:
      projectID: gkem-api-new
      auth:
        workloadIdentity:
          # name of the cluster Location, region or zone
          clusterLocation: us-central1
          # name of the GKE cluster
          clusterName: cluster-1
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
         
          # reference the sa from above
          serviceAccountRef:
            name: quote-secrets-sa 
           