apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-app
  namespace: app
  labels:
    app: my-app
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
        - name: cnt-1
          image: gcr.io/nanna-398608/prom-app # Replace with your container image and tag
          ports:
            - containerPort: 8080 # Replace with the port your application listens on
              name: scrape
---
apiVersion: v1
kind: Service
metadata:
   name: prom-app
   namespace: app
   labels:
       app: prom-service
       job: prom-demo
spec:
   type: LoadBalancer
   selector:
     app: prom
   ports:
   - port: 80
     targetPort: 8080
     name: web
