apiVersion: apps/v1
kind: Deployment 
metadata:
   name: prod-app
   namespace: prod
spec:
   replicas: 1
   selector:
       matchLabels:
          app: prod
   template:
       metadata:
          labels:
             app: prod
       spec:
         containers:
         - name: cnt-1
           image: gcr.io/argo-gke/start
           ports:
           - containerPort: 8080

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod

