apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app: my-app
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: skaffold
  template:
    metadata:
      labels:
        app: skaffold
    spec:
      containers:
        - name: cnt-1
          image: gcr.io/helm-pract/skaffold-app # Replace with your container image and tag
          ports:
            - containerPort: 8080 # Replace with the port your application listens on
              name: scrape
