{{- if .Values.quote_api_service }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quote-api-external-secret
  namespace: {{ .Values.external_secrets.namespace }}
  annotations:
     "helm.sh/hook": "post-install"
     "helm.sh/hook-weight": "1"

spec:
  refreshInterval: 10s         # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: gcp-secret-store               # name of the SecretStore (or kind specified)
  target:
    name: {{ .Values.quote_api_service.secretRef}} # name of the k8s Secret to be created
    creationPolicy: Owner

  data:
  - secretKey: QUOTES_API_URL 
    remoteRef:
      key: API_HOST_URL   # name of the GCPSM secret key
  - secretKey: QUOTES_API_KEY 
    remoteRef:
       key: API_KEY 
{{- end }}