{{- if .Values.quote_api_service.create }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: {{.Values.external_secrets.namespace }}
  annotations:
     "helm.sh/hook": "post-install"
    

      

spec:
  provider:
    gcpsm:
      projectID: {{.Values.external_secrets.Project_ID}}
      auth:
        workloadIdentity:
          # name of the cluster Location, region or zone
          clusterLocation: {{.Values.external_secrets.Cluster_Location}}
          # name of the GKE cluster
          clusterName: {{.Values.external_secrets.Cluster_Name}}
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
         
          # reference the sa from above
          serviceAccountRef:
            name: {{.Values.external_secrets.k8s_sa}}
           
{{-  end }}