{{- if .Values.quote_api_service.create }}
apiVersion: v1
kind: Service 
metadata:
    name: quote-api-svc-canary 
    namespace: {{ .Values.quote_api_service.namespace }}
    
spec:
  type: ClusterIP
  {{- with .Values.quote_api_service.labels }}
  selector:
    {{- toYaml . | nindent 10 }}
  {{- end }}
  
   
  ports:
  - port: 80
    targetPort: 8080
    name: http-web
---

apiVersion: v1
kind: Service 
metadata:
    name: quote-api-svc-stable
    namespace: {{ .Values.quote_api_service.namespace }}
    
spec:
  type: ClusterIP
  {{- with .Values.quote_api_service.labels }}
  selector:
    {{- toYaml . | nindent 10 }}
  {{- end }}
  
   
  ports:
  - port: 80
    targetPort: 8080
    name: http-web
 
{{- end }}

