{{- if .Values.quote_api_service.create}}
apiVersion: v1
kind: ServiceAccount
metadata:
   name: {{.Values.external_secrets.k8s_sa}} 
   namespace: {{.Values.external_secrets.namespace}}
   annotations:
      iam.gke.io/gcp-service-account: {{.Values.external_secrets.gcp_sa}}
      
{{- end }}