{{- if .Values.quote_api_service.create }}
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: quote-api-gateway 
  namespace: {{.Values.quote_api_service.namespace}}
spec:
  gatewayClassName: gke-l7-regional-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
{{- end }}