name:  IMAGE_PUSHER
run-name: image_pusher 
on:
    push:
      paths:
      - app/**

jobs:
     push_image_to_registry:
          runs-on: ubuntu-latest 
          permissions:
            contents: 'read'
            id-token: 'write'
          steps:
          - name: starting_step
            
            run:  "echo 'WORKFLOW STARTED'"
          - name: github checkout 
            run:  actions/checkout@v2
          - run: "ls"


        
    