name:  IMAGE_PUSHER
run-name: image_pusher 
on:
    push:
      paths:
      - app/**

jobs:
     push_image_to_registry:
          runs-on: ubuntu-latest 
          permissions:
            contents: 'read'
            id-token: 'write'
          steps:
          - name: starting_step
            
            run:  "echo 'WORKFLOW STARTED'"
          - name: github checkout 
            uses:  actions/checkout@v2
          - name: Google Auth
            id: google_auth
            uses: 'google-github-actions/auth@v0'
            with:
             token_format: 'access_token'
             workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' 
             service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
          - name: docker-login
            id: docker_login
            
            uses: 'docker/login-action@v1'
            with:
             username: 'oauth2accesstoken'
             password: '${{ steps.google_auth.outputs.access_token }}'
             registry: '${GAR_LOCATION}-docker.pkg.dev'
          - name: Build and Push container 
            id: push_container
            run: |
               export DOCKER_IMAGE_URL="${GAR_LOCATION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}:${{ github.sha }}"
               echo $DOCKER_IMAGE_URL
               docker build -t $DOCKER_IMAGE_URL  app/
               docker push $DOCKER_IMAGE_URL
               echo "image_url=${DOCKER_IMAGE_URL}" >> "$GITHUB_OUTPUT"
     replace_image_tag:
         runs-on: ubuntu-latest 
         needs:
         - push_image_to_registry
         steps:
         - name: print image_url 
           run: |
               echo "${{needs.push_image_to_registry.outputs.image_url}}"
        

          

    