name:  IMAGE_PUSHER
run-name: image_pusher 
on:
    push:
      paths:
      - app/**

jobs:
     push_image_to_registry:
          runs-on: ubuntu-latest 
          outputs:
             image_url: "${{steps.push_container.outputs.image_url}}"
          permissions:
            contents: 'read'
            id-token: 'write'
          steps:
          - name: starting_step
            
            run:  "echo 'WORKFLOW STARTED'"
          - name: github checkout 
            uses:  actions/checkout@v2
          - name: Google Auth
            id: google_auth
            uses: 'google-github-actions/auth@v0'
            with:
             token_format: 'access_token'
             workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' 
             service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
          - run : "echo ${{vars.GAR_LOCATION  }}"
          - name: docker-login
            id: docker_login
            
            uses: 'docker/login-action@v1'
            with:
             username: 'oauth2accesstoken'
             password: '${{ steps.google_auth.outputs.access_token }}'
             registry: '${{vars.GAR_LOCATION}}-docker.pkg.dev'
          - name: Build and Push container 
            id: push_container
            run: |
               export DOCKER_IMAGE_URL="${{vars.GAR_LOCATION}}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{vars.GAR_REPOSITORY}}/quote-api:${GITHUB_SHA}"
               
               docker build -t $DOCKER_IMAGE_URL  app/
               docker push $DOCKER_IMAGE_URL
               echo "image_url=${DOCKER_IMAGE_URL}" >> "$GITHUB_OUTPUT"
          - name: print output
            run : echo "${{steps.push_container.outputs}}"
     replace_image_tag:
         runs-on: ubuntu-latest 
         needs:
         - push_image_to_registry
         steps:
         - name: print image_url 
           run: |
               echo "${{needs.push_image_to_registry.outputs.image_url}}"
         - name: github checkout 
           uses:  actions/checkout@v2
         - name: replace the image tag 
           run: |
              
                sed -i "s/\(${{vars.GAR_LOCATION}}-docker.pkg.dev\/${PROJECT_ID}\/${{vars.GAR_REPOSITORY}}\/quote-api:\)[^ ]*/\1${GITHUB_SHA}/g" quote-api-helm-chart/templates/quote_api/rollout.yaml
        
         - name: commit files 
           run: |
                git checkout main
                git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                git add quote-api-helm-chart/templates/quote_api/rollout.yaml
                git commit -m "updated image tag of quote-api service"

         - name: push_to_repo 
           uses: ad-m/github-push-action@master
           with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}

          

    